"""Regenerate the README performance section from the data.

The previous README carried a performance table that no script in the
repository could reproduce, contained figures that contradicted each other
(HO's stated "overall historical average of 94.8%" fell outside its own stated
60-79% envelope), and quoted dollar totals that assumed a full 8,500-gallon
truck on every one of ~300 alerts a year.

Every number this emits is computed here, from the alignment-verified history,
out of sample, with an interval attached.  Run it and paste the block between
the BEGIN/END markers in README.md, or use --check in CI to fail when the
README has drifted from the data.
"""

import argparse
import re
import sys

import numpy as np
from scipy import stats

import alignment
import backtest
import model
from futures_util import is_contract_roll_day

BEGIN = "<!-- BEGIN GENERATED PERFORMANCE -->"
END = "<!-- END GENERATED PERFORMANCE -->"

TRUCK_GALLONS = 8500
NAMES = {"RB": "Unleaded gasoline (RBOB)", "HO": "Diesel / heating oil (HO)"}


def wilson(successes, trials, z=1.959963985):
    if not trials:
        return float("nan"), float("nan")
    p = successes / trials
    denom = 1 + z * z / trials
    centre = (p + z * z / (2 * trials)) / denom
    margin = (z / denom) * np.sqrt(p * (1 - p) / trials + z * z / (4 * trials * trials))
    return max(0.0, centre - margin), min(1.0, centre + margin)


def pairs(prefix, df):
    frame = alignment.aligned_deltas(df, prefix)
    keep = ~frame["date"].apply(lambda d: is_contract_roll_day(d.date(), prefix))
    return frame[keep].reset_index(drop=True)


def rolling_out_of_sample(frame, cfg, window=None, step=10):
    """Expanding-origin evaluation: fit on the past, score the next block.

    The window defaults to the configured ROLLING_WINDOW_DAYS so the published
    figures describe the model that actually runs, not a different one.
    """
    window = int(window or cfg["ROLLING_WINDOW_DAYS"])
    alerts = correct = 0
    total = 0.0
    payoffs = []
    first = last = None
    for start in range(120, len(frame), step):
        train = frame.iloc[max(0, start - window):start]
        test = frame.iloc[start:start + step]
        if len(train) < model.MIN_FIT_ROWS or test.empty:
            continue
        fit = model.fit_passthrough(train["delta_nymex"], train["delta_rack"])
        hike, drop = model.apply_noise_floor(
            *fit.threshold_for_confidence(cfg["TARGET_SIGNAL_CONFIDENCE"]),
            cfg["SNAPSHOT_NOISE_FLOOR_CENTS"])
        summary = model.summarize(test["delta_nymex"], test["delta_rack"], hike, drop)
        alerts += summary["alerts"]
        correct += summary["correct"]
        total += summary["total_savings"]
        payoffs.extend(summary["payoff"].tolist())
        first = first or test["date"].iloc[0]
        last = test["date"].iloc[-1]

    payoffs = np.array(payoffs)
    wins = payoffs[payoffs > 0]
    losses = payoffs[payoffs < 0]
    lo, hi = wilson(correct, alerts)
    # Bootstrap the mean payoff: a handful of large moves dominate the total,
    # so the point estimate on its own is misleading.
    rng = np.random.default_rng(20260917)
    boot = rng.choice(payoffs, size=(4000, len(payoffs)), replace=True).mean(axis=1)
    return {
        "alerts": alerts,
        "precision": correct / alerts if alerts else float("nan"),
        "precision_low": lo,
        "precision_high": hi,
        "mean_savings": float(payoffs.mean()) if payoffs.size else float("nan"),
        "mean_low": float(np.percentile(boot, 2.5)),
        "mean_high": float(np.percentile(boot, 97.5)),
        "median_savings": float(np.median(payoffs)) if payoffs.size else float("nan"),
        "win": float(wins.mean()) if wins.size else float("nan"),
        "loss": float(-losses.mean()) if losses.size else float("nan"),
        "sessions": len(frame),
        "start": first.date().isoformat() if first is not None else "?",
        "end": last.date().isoformat() if last is not None else "?",
    }


def regime_split(frame, cfg):
    fit = model.fit_passthrough(frame["delta_nymex"], frame["delta_rack"])
    hike, drop = model.apply_noise_floor(
        *fit.threshold_for_confidence(cfg["TARGET_SIGNAL_CONFIDENCE"]),
        cfg["SNAPSHOT_NOISE_FLOOR_CENTS"])
    volatility = frame["delta_nymex"].abs()
    cut = float(volatility.median())
    out = {}
    for label, mask in (("calm", volatility <= cut), ("volatile", volatility > cut)):
        subset = frame[mask]
        out[label] = model.summarize(subset["delta_nymex"], subset["delta_rack"], hike, drop)
    out["cut"] = cut
    return out


def build(cfg=None):
    cfg = cfg or backtest.load_config()
    for key, value in backtest.DEFAULTS.items():
        cfg.setdefault(key, value)
    full = alignment.load_history()
    report = alignment.assert_calibration_alignment(full)
    df = alignment.calibration_history(full)

    lines = [BEGIN, ""]
    lines.append("> Generated by `python3 generate_readme_stats.py`. Do not edit by hand.")
    lines.append(f"> Verified history: **{len(df)} sessions**, "
                 f"{df['date'].min().date()} to {df['date'].max().date()}.")
    lines.append("")
    lines.append("### Measured performance")
    lines.append("")
    lines.append("Expanding-origin out-of-sample: the model is fitted only on sessions "
                 "before each scored block, and no parameter is selected by comparing "
                 "blocks. Intervals are 95%.")
    lines.append("")
    lines.append("| | Alerts | Precision | ¢/alert (mean) | ¢/alert (median) | Avg win | Avg loss |")
    lines.append("|---|---|---|---|---|---|---|")

    results = {}
    for prefix in ("RB", "HO"):
        frame = pairs(prefix, df)
        result = rolling_out_of_sample(frame, cfg)
        results[prefix] = result
        lines.append(
            f"| {NAMES[prefix]} | {result['alerts']} | "
            f"{result['precision']:.1%} ({result['precision_low']:.0%}–{result['precision_high']:.0%}) | "
            f"{result['mean_savings']:+.2f} ({result['mean_low']:+.2f} to {result['mean_high']:+.2f}) | "
            f"{result['median_savings']:+.2f} | {result['win']:.2f}¢ | {result['loss']:.2f}¢ |")

    lines.append("")
    lines.append(f"Scored window: {results['RB']['start']} to {results['RB']['end']}.")
    lines.append("")

    lines.append("### What one alert is worth")
    lines.append("")
    lines.append("Per-gallon, on the volume you actually shift that day. A full "
                 f"{TRUCK_GALLONS:,}-gallon load is shown for scale only — it is **not** a "
                 "claim that you lift a full truck on every alert.")
    lines.append("")
    lines.append("| | ¢/gal per alert | $ per 8,500-gal load | $ per 1,000 gal |")
    lines.append("|---|---|---|---|")
    for prefix in ("RB", "HO"):
        mean = results[prefix]["mean_savings"]
        lines.append(f"| {NAMES[prefix]} | {mean:+.2f}¢ | "
                     f"${mean / 100 * TRUCK_GALLONS:,.0f} | ${mean / 100 * 1000:,.0f} |")
    lines.append("")
    lines.append("Multiply by the loads you genuinely reschedule. Summing every alert and "
                 "multiplying by a full truck implies buying ahead on ~300 days a year, "
                 "which needs storage no single site has.")
    lines.append("")

    lines.append("### Regime dependence")
    lines.append("")
    lines.append("Splitting the verified history at its median absolute NYMEX move:")
    lines.append("")
    lines.append("| | Calm sessions | Volatile sessions |")
    lines.append("|---|---|---|")
    for prefix in ("RB", "HO"):
        split = regime_split(pairs(prefix, df), cfg)
        lines.append(
            f"| {NAMES[prefix]} | {split['calm']['alerts']} alerts, "
            f"{split['calm']['precision']:.0%}, {split['calm']['mean_savings']:+.2f}¢/alert | "
            f"{split['volatile']['alerts']} alerts, {split['volatile']['precision']:.0%}, "
            f"{split['volatile']['mean_savings']:+.2f}¢/alert |")
    lines.append("")
    lines.append("**Size decisions on the calm column.** Precision is higher when moves "
                 "are large, because the pass-through signal grows relative to the rack's "
                 "fixed noise floor. The calm column is what a normal market looks like "
                 "and is roughly a third of the cents per alert. These figures span "
                 "three years and both regimes, so the headline is an average of the two "
                 "rather than an extrapolation from one.")
    lines.append("")

    lines.append("### Fitted pass-through")
    lines.append("")
    lines.append("| | Slope | Intercept | R² | Residual σ | Sessions |")
    lines.append("|---|---|---|---|---|---|")
    for prefix in ("RB", "HO"):
        fit = model.fit_passthrough(*[pairs(prefix, df)[c] for c in ("delta_nymex", "delta_rack")])
        lines.append(f"| {NAMES[prefix]} | {fit.slope:.3f} | {fit.intercept:+.3f}¢ | "
                     f"{fit.r2:.3f} | {fit.sigma:.2f}¢ | {fit.n} |")
    lines.append("")
    lines.append(f"Alignment check: " + "; ".join(
        f"{p} lag-1 coefficient {report[p]['b1']:+.3f} (p={report[p]['p_b1']:.2f}, "
        f"{report[p]['ratio']:.0%} of same-session)" for p in ("RB", "HO")) + ".")
    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="update README.md in place")
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if README.md is stale")
    args = parser.parse_args()

    block = build()
    if not (args.write or args.check):
        print(block)
        return

    with open("README.md", "r", encoding="utf-8") as handle:
        readme = handle.read()
    if BEGIN not in readme or END not in readme:
        print("README.md has no generated-performance markers.")
        sys.exit(1)
    updated = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block.replace("\\", "\\\\"),
                     readme, flags=re.S)

    if args.check:
        if updated != readme:
            print("README.md performance section is stale; run "
                  "`python3 generate_readme_stats.py --write`.")
            sys.exit(1)
        print("README.md performance section is current.")
        return

    with open("README.md", "w", encoding="utf-8") as handle:
        handle.write(updated)
    print("README.md performance section updated.")


if __name__ == "__main__":
    main()
